import = [
  "~/.config/alacritty/tokyonight_night.toml"
]

[env]
# TERM = "xterm-256color"
#TERM = "xterm-kitty"

[window]
opacity = 0.9
padding.x = 5
padding.y = 5

[scrolling]
history = 100000

[font]
# "Monaspace Neon" if font healing is supported
normal = {family = "MesloLGS NF"}

[colors]
transparent_background_colors = true

[selection]
semantic_escape_chars = ",│‘|:\"' ()[]{}<>\t="
# Tilix was reverese and defined what combined words: -,./?%&#_~*
