import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9

[scrolling]
history = 100000

[font.normal]
# Monaspace Neon (try if healing works)
family = "MesloLGS NF"

[colors]
transparent_background_colors = true
