import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
# TERM = "xterm-256color"
TERM = "xterm-kitty"

[window]
opacity = 0.9

[scrolling]
history = 100000

[font]
# "Monaspace Neon" if font healing is supported
normal = {family = "MesloLGS NF"}

[colors]
transparent_background_colors = true
