[general]
import = [
  "~/.config/alacritty/tokyonight_night.toml"
]

[cursor]
thickness = 0.11
blink_interval = 600
blink_timeout = 0
vi_mode_style.shape = "Block"

[env]
# TERM = "xterm-256color"
#TERM = "xterm-kitty"

[window]
opacity = 0.9
padding.x = 5
padding.y = 5

[scrolling]
history = 100000

[font]
# "Monaspace Neon" if font healing is supported
normal.family = "MesloLGS NF"
size = 12

[colors]
transparent_background_colors = true

[selection]
semantic_escape_chars = ",│‘|:\"' ()[]{}<>\t="
# Tilix was reverese and defined what combined words: -,./?%&#_~*
